name: dashboard
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #STATE MANAGEMENT
  provider: 6.1.2

  #ROUTING
  fluro: 2.0.5

  # RESPONSIVE SCREEN
  responsive_framework: 1.4.0

  #UTILITIES
  url_strategy: 0.2.0 # URL Strategy
  encrypt: 5.0.3 # Encrypt
  intl: 0.19.0 # Intl
  file_picker: 8.0.3 # File Picker
  device_info_plus: 10.1.0 # Device Info
  flutter_secure_storage: 9.0.0 # Secure Storage
  path: 1.9.0

  #CONFIG
  flutter_flavor: 3.1.3 #Config for mode app (DEV or PROD)

  #UI PACKAGE
  carousel_slider: 4.2.1 # Carousel Slider
  popover: 0.3.0 # Show Popover

  #MORE PACKAGE
  selectable: 0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 8.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/icons/icon_app.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Gothic
      fonts:
        - asset: assets/fonts/Gothic-Regular.ttf
        - asset: assets/fonts/Gothic-Bold.ttf
